# Generated by Django 3.0.6 on 2020-06-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20200617_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
